language: ruby
rvm:
- 2.0.0
- 1.9.3
before_install: gem install bundler -v 1.11.2
before_script: bundle exec berks vendor -d
script: bundle exec strainer test --except kitchen -p $PWD/berks-cookbooks/ -d
notifications:
  slack:
    secure: il5rpAZCNPhfsXVijr7kcg42cA0hH7P6zXvfuXaCSbSbme1fmz5Vh/INmir8nrnTyxEELZ2+M8qJJuH/qIjTeM02n/q9pkklOHnmyN2D5jhTc9ZtRjZPy4YMmYo/uYXsx8QzcD8YWvI/WO8+Xec9OixY43ct0aAUCRqX4IX67hQ=
